### ISSUE TITLE
ERR_CONTENT_DECODING_FAILED when accessing Configuration page

### ISSUE THREAD

**Issue by henno** [Sajaki/RecentTopics#74]
### Expected Behavior
Going to ACP > Extensions > Recent Topics > Configuration shows RT config page

### Actual Behavior
Going to ACP > Extensions > Recent Topics > Configuration shows an error:
This site can’t be reached

The web page at https://example.com/adm/index.php?sid=102c6d26b9e5bd3cca9c27b17acbdfef&i=-paybas-recenttopics-acp-recenttopics_module&mode=recenttopics_config might be temporarily down or it may have moved permanently to a new web address.
ERR_CONTENT_DECODING_FAILED
(the browser is Google Chrome)

### Steps to Reproduce the Problem

  1. Install Recent Topics extension and enable it
  1. Click Extensions
  1. Click on Configuration under Recent Topics (the aforementioned error is shown)
  1. Google error. You'll find that the content is not encoded while the server tells the brauser that it is.
  1. Enable zlib compression in php.ini and try again. You'll see a debug message on every ACP page, except RT Configuration, which now works. 

### Specifications

  - phpbb version: 3.2.1
  - recenttopics version: 2.2.5

**Comment by Galixte** [comment]
@henno, it’s not an extension error, it’s related to the requirements needed for using phpBB, see here: https://www.phpbb.com/community/viewtopic.php?f=556&t=2429146.

You have to disable the setting: “Enable GZip compression”, In ACP->Server settings, purge the cache and try again to see the situation improved.

Source: https://www.phpbb.com/community/viewtopic.php?f=556&t=2414971.

**Comment by avandenberghe** [comment]
if you enable zlib in php.ini (zlib.output_compression = On)
then you should also disable “Enable GZip compression" in the ACP otherwise you get error 
[phpBB Debug] PHP Warning: in file [ROOT]/includes/functions_acp.php on line 65: ob_start(): output handler 'ob_gzhandler' conflicts with 'zlib output compression'
[phpBB Debug] PHP Notice: in file [ROOT]/includes/functions_acp.php on line 65: ob_start(): failed to create buffer. 

but I could't reproduce the ERR_CONTENT_DECODING_FAILED in recenttopics acp when zlib is off and gzip is on or off, using chrome.
